services:
  api:
    image: pet-project-api
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    command: sh -c "bunx prisma migrate deploy --schema=prisma/schema/schema.prisma && node dist/src/main.js"

  web:
    image: pet-project-web
    ports:
      - "3000:3000"
    depends_on:
      - api
